import json
from dataclasses import asdict, dataclass, field
from typing import Any

from langchain_core.messages import BaseMessage


@dataclass
class GraphState:
    """
    Represents the complete mutable state of a single LLM reasoning workflow.

    Attributes:
        user_messages: Ordered list of user and system messages exchanged in the current session.
        script: The script generated by the LLM.
        script_explanation: Natural-language explanation or rationale behind the generated script.
        script_result: Raw result data returned after executing the  script on the graph database.
        script_evaluation: Binary or qualitative evaluation of the generated script's correctness or relevance.
        script_feedback: Detailed LLM-generated feedback describing issues or improvements for the script.
        response_interpretation: Natural-language interpretation of the script result for end-user presentation.
        hallucination_fix_instructions: Model-generated guidance for correcting detected hallucinations or inconsistencies.
        errors: Any runtime, validation, or execution errors captured during node processing or script execution.
        num_of_generation_attempts: Counter tracking how many times the LLM attempted to generate or refine the script.
        max_generation_attempts_achieved: If we achieved the iterations threwshold.
    """
    user_messages: list[BaseMessage] = field(default_factory=list)
    script: str | None = None
    script_explanation: str | None = None
    script_result: Any | None = None
    script_evaluation: str | None = None
    script_feedback: Any | None = None
    response_interpretation: str | None = None
    hallucination_fix_instructions: str | None = None
    errors: Any | None = None
    num_of_generation_attempts: int = field(default=0)
    max_generation_attempts_achieved: bool = False

    def to_pretty_json(self) -> str:
        """Return a JSON-formatted string of the state with serializable messages."""
        data = asdict(self)
        data["user_messages"] = [
            {"type": msg.type, "content": msg.content, "metadata": msg.response_metadata, "kwargs": msg.additional_kwargs}
            for msg in self.user_messages
        ]
        return json.dumps(data, indent=4, ensure_ascii=False)
    

@dataclass
class MySubgraphState:
    """
    The state of the  entities validation and correction workflow.

    Attributes:
        script: Generated  script.
        extracted_entities: List of entities to validate or correct.
        node_labels_validation_res: Generated  script for validation or correction.
        node_props_validation_res: for not found entities - similar entities found in the database.
        hallucination_fix_instructions: Instructions for the Generator to fix any identified hallucinations.
    """
    script: str
    extracted_entities: Any | None = None
    node_labels_validation_res: Any | None = None
    node_props_validation_res: Any | None = None
    relationships_validation_res: Any | None = None
    hallucination_fix_instructions: str | None = None
